sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /zed/point_cloud/cloud_registered
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.00
    padding_scale: 0.1
    filtered_cloud_topic: filtered_cloud